apiVersion: v1
kind: Service
metadata:
  name: service-ip-cluster
spec:
  type: ClusterIP
  selector:
    app: service-ip-cluster
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
